version: '3'
services:
  hubot:
    build: .
    environment:
      - NODE_ENV=development
      - HUBOT_SLACK_TOKEN
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
  redis:
    image: "redis:3-alpine"
